<template>
    <aside class="enrollment-summary-card">
        <div class="summary-cover">
            <span class="summary-kicker">{{ $t('lms.registrationProfile') }}</span>
            <div class="summary-avatar">{{ initials }}</div>
        </div>

        <div class="summary-content">
            <h2>{{ studentName || $t('lms.newStudent') }}</h2>
            <p>{{ studentCode || $t('lms.notSelected') }}</p>
            <el-tag :type="statusMeta.type" effect="light" round>{{ statusMeta.label }}</el-tag>

            <div class="summary-progress">
                <div>
                    <span>{{ $t('lms.progress') }}</span>
                    <strong>{{ progress }}%</strong>
                </div>
                <el-progress :percentage="progress" :show-text="false" :stroke-width="8" />
            </div>

            <div class="summary-list">
                <div class="summary-item">
                    <el-icon><Reading /></el-icon>
                    <div>
                        <span>{{ $t('lms.course') }}</span>
                        <strong>{{ courseName || $t('lms.notSelected') }}</strong>
                    </div>
                </div>
                <div class="summary-item">
                    <el-icon><Calendar /></el-icon>
                    <div>
                        <span>{{ $t('lms.enrolledAt') }}</span>
                        <strong>{{ formattedDate }}</strong>
                    </div>
                </div>
                <div class="summary-item">
                    <el-icon><DocumentChecked /></el-icon>
                    <div>
                        <span>{{ $t('lms.enrollmentCode') }}</span>
                        <strong>{{ enrollmentId ? `#${enrollmentId}` : $t('lms.autoGenerated') }}</strong>
                    </div>
                </div>
            </div>
        </div>
    </aside>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Calendar, DocumentChecked, Reading } from '@element-plus/icons-vue'
import { useI18n } from 'vue-i18n'
import type { EnrollmentStatus } from '/@/types/lms/enrollment'

const props = withDefaults(
    defineProps<{
        enrollmentId?: number
        studentName?: string
        studentCode?: string
        courseName?: string
        enrolledAt?: string
        status?: EnrollmentStatus
        progress?: number
    }>(),
    {
        studentName: '',
        studentCode: '',
        courseName: '',
        enrolledAt: '',
        status: 'ENROLLED',
        progress: 0,
    }
)
const { t, locale } = useI18n()

const statusMap: Record<EnrollmentStatus, { label: string; type: 'success' | 'warning' | 'info' | 'danger' }> = {
    ENROLLED: { label: 'lms.enrolled', type: 'info' },
    LEARNING: { label: 'lms.learning', type: 'warning' },
    COMPLETED: { label: 'lms.completed', type: 'success' },
    CANCELLED: { label: 'lms.cancelled', type: 'danger' },
}

const statusMeta = computed(() => ({ ...statusMap[props.status], label: t(statusMap[props.status].label) }))
const initials = computed(() => {
    const parts = props.studentName.trim().split(/\s+/).filter(Boolean)
    if (!parts.length) return t('lms.studentInitialFallback')
    return parts
        .slice(-2)
        .map((part) => part[0])
        .join('')
        .toUpperCase()
})
const formattedDate = computed(() => {
    if (!props.enrolledAt) return t('lms.noData')
    const date = new Date(props.enrolledAt)
    return Number.isNaN(date.getTime()) ? props.enrolledAt : new Intl.DateTimeFormat(locale.value === 'en' ? 'en-US' : 'vi-VN').format(date)
})
</script>

<style scoped lang="scss">
.enrollment-summary-card {
    overflow: hidden;
    align-self: start;
    position: sticky;
    top: 84px;
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 16px;
    box-shadow: 0 8px 28px rgb(15 23 42 / 6%);
}

.summary-cover {
    position: relative;
    height: 126px;
    padding: 22px;
    color: #fff;
    background: linear-gradient(135deg, var(--el-color-primary), #2563eb 52%, #60a5fa);
}

.summary-cover::after {
    position: absolute;
    right: -36px;
    bottom: -54px;
    width: 150px;
    height: 150px;
    content: '';
    border: 28px solid rgb(255 255 255 / 11%);
    border-radius: 50%;
}

.summary-kicker {
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.13em;
    opacity: 0.86;
}

.summary-avatar {
    position: absolute;
    bottom: -43px;
    left: 50%;
    z-index: 1;
    display: grid;
    width: 88px;
    height: 88px;
    font-size: 25px;
    font-weight: 700;
    color: var(--el-color-primary);
    background: #eff6ff;
    border: 5px solid #fff;
    border-radius: 50%;
    box-shadow: 0 8px 24px rgb(15 23 42 / 18%);
    place-items: center;
    transform: translateX(-50%);
}

.summary-content {
    padding: 56px 24px 26px;
    text-align: center;
}

.summary-content h2 {
    margin: 0 0 5px;
    font-size: 19px;
    color: var(--el-text-color-primary);
}

.summary-content > p {
    margin: 0 0 13px;
    font-size: 13px;
    color: var(--el-text-color-secondary);
}

.summary-progress {
    padding: 18px 0;
    margin-top: 20px;
    border-top: 1px solid var(--el-border-color-lighter);
    border-bottom: 1px solid var(--el-border-color-lighter);
    text-align: left;
}

.summary-progress > div {
    display: flex;
    justify-content: space-between;
    margin-bottom: 9px;
    font-size: 13px;
}

.summary-list {
    display: grid;
    gap: 17px;
    padding-top: 21px;
    text-align: left;
}

.summary-item {
    display: flex;
    gap: 12px;
    align-items: flex-start;
}

.summary-item > .el-icon {
    flex: 0 0 auto;
    width: 32px;
    height: 32px;
    color: var(--el-color-primary);
    background: var(--el-color-primary-light-9);
    border-radius: 9px;
}

.summary-item div {
    display: grid;
    min-width: 0;
    gap: 4px;
}

.summary-item span {
    font-size: 12px;
    color: var(--el-text-color-secondary);
}

.summary-item strong {
    overflow: hidden;
    font-size: 13px;
    color: var(--el-text-color-primary);
    text-overflow: ellipsis;
    white-space: nowrap;
}

@media (max-width: 960px) {
    .enrollment-summary-card {
        position: static;
    }
}
</style>
